return {
	[1] = {
		Beaks = 300,
		Eggs = {},
		Pigeons = {}
	},
	[2] = {
		Beaks = 0,
		Eggs = { "Kingdom" },
		Pigeons = {}
	},
	[3] = {
		Beaks = 75000,
		Eggs = {},
		Pigeons = {}
	},
	[4] = {
		Beaks = 0,
		Eggs = { "Candy" },
		Pigeons = {}
	},
	[5] = {
		Beaks = 180000,
		Eggs = {},
		Pigeons = {}
	},
	[6] = {
		Beaks = 400000,
		Eggs = {},
		Pigeons = {}
	},
	[7] = {
		Beaks = 0,
		Eggs = { "Space" },
		Pigeons = {}
	},
	
}


