return {
    SpawnCooldown = 3.5, -- How often eggs should spawn
	Duration = 40, -- How long eggs take to reach the end
    PityTimes = {
        Rare = 30,
		Epic = 40,
		Beach = 52,
		Miner = 60 * 3 + 5,
		Kingdom = 60*5,
		Candy = 60 * 10 + 5,
		Nature = 60*15 + 10,
		Winter = 60*20 + 30,
		Volcano = 60*30,
		Pumpkin = 60*35 + 45,
		--Secret = 60*180
	},
	
	RarityRates = {
		Common   = 320,
		Uncommon = 195,
		Rare     = 96,
		Epic     = 46.5,
		Beach    = 25.1,
		Miner    = 7.65,
		Kingdom  = 5.45,
		Nature   = 2.65,
		Candy    = 2,
		Volcano  = 1.65,
		Winter   = 0.9,
		Pumpkin  = 0.85,
		Zombie   = 0.6,
		Glitched = 0.5,
		Space    = 0.35,
		Secret   = 0.3,
	}




	
	--[[RarityRates = {
		Common   = 340,
		Uncommon = 188,
		Rare     = 129,
		Epic     = 48, 
		Beach    = 24,
		Miner    = 6.25,
		Kingdom  = 1.5,
		Nature = 0.53,
		Candy = 0.29,
		Volcano = 0.08,
		Winter = 0.052,
		Pumpkin = 0.028,
		Zombie   = 0.05, 
		Glitched = 0.029,
		Space = 0.009,
		Secret   = 0.0053,
	}]]

}