return {
	--[[["Bat"] = {
		Description = "A basic weapon used to hit opponents at close range.",
		Icon = "rbxassetid://4932995303",
		Price = 2250,
		StockChance = 75,
		StockAmount = {1, 1},
		MaxTools = 1,
		Saves = false,
		LayoutOrder = 2
	},]]
    ["Gold Spray"] = {
        Icon = "rbxassetid://117948519336681",
        MaxTools = 3,
        Saves = true,
    },
    ["Wealth Spray"] = {
        Icon = "rbxassetid://75265554947975",
        MaxTools = 3,
        Saves = true,
    },
    ["Flying Carpet"] = {
        Icon = "rbxassetid://83011814298635",
        MaxTools = 1,
        Saves = true,
    },
	["Luck Spray"] = {
		Description = "A spray that boosts your egg luck [Used on Eggs].",
		Icon = "rbxassetid://83011814298635",
		Price = 20000,
		StockChance = 10,
		StockAmount = {1, 2},
		MaxTools = 5,
		Saves = true,
		LayoutOrder = 8,
		BoughtWithRobux = true,
        ID = 3436247816
	},
	["Shock Spray"] = {
		Description = "A Spray that gives any pigeon the Shocked Mutation [Used on Pigeons].",
		Icon = "rbxassetid://115075898921335",
		Price = 20000,
		StockChance = 10,
		StockAmount = {1, 2},
		MaxTools = 3,
		Saves = true,
		LayoutOrder = 7,
		BoughtWithRobux = true,
		ID = 3436245965
	},
	["Size Spray"] = {
		Description = "A spray that boosts your pigeon's Size [Used on Eggs].",
		Icon = "rbxassetid://123196272315440",
        Price = 30000,
		StockChance = 9,
		StockAmount = {1, 2},
		MaxTools = 5,
		Saves = true,
		LayoutOrder = 9,
		BoughtWithRobux = true,
		ID = 3436247492
	},
	["Slap"] = {
		Description = "A tool that can be used to knockback people",
		Icon = "rbxassetid://74260517130409",
		Price = 800,
		StockChance = 100,
		StockAmount = {1, 1},
		MaxTools = 1,
		Saves = false,
		LayoutOrder = 1,
		BoughtWithRobux = false,
		ID = 0
	},
	["Speed Coil"] = {
		Description = "Gives a boost of speed when equipped.",
		Icon = "rbxassetid://103083613259354",
		Price = 2000,
		StockChance = 80,
		StockAmount = {1, 1},
		MaxTools = 1,
		Saves = false,
		LayoutOrder = 4,
		BoughtWithRobux = false,
		ID = 0
		
	},
	["Invisibility Cloak"] = {
		Description = "Makes you invisible when equipped.",
		Icon = "rbxassetid://110556306449446",
		Price = 15000,
		StockChance = 45,
		StockAmount = {1, 1},
		MaxTools = 1,
		Saves = false,
		LayoutOrder = 7,
		BoughtWithRobux = false,
		ID = 0

	},
	["Body Swap"] = {
		Description = "Swap places with any player, but a 50s cooldown.",
		Icon = "rbxassetid://79344387310152",
		Price = 7000,
		StockChance = 50,
		StockAmount = {1, 1},
		MaxTools = 1,
		Saves = false,
		LayoutOrder = 5,
		BoughtWithRobux = false,
		ID = 0
	},
	["Trap"] = {
		Description = "A Trap that stuns people for 4 seconds",
		Icon = "rbxassetid://86434754851847",
		Price = 1500,
		StockChance = 100,
		StockAmount = {1, 3},
		MaxTools = 3,
		Saves = false,
		LayoutOrder = 3,
		BoughtWithRobux = false,
		ID = 0
	},
	["Volcanic Spray"] = {
		Description = "A Spray that gives any pigeon the Volcanic Mutation [Used on Pigeons].",
		Icon = "rbxassetid://86675217102611",
		Price = 12000,
		StockChance = 15,
		StockAmount = {1, 1},
		MaxTools = 3,
		Saves = true,
		LayoutOrder = 6,
		BoughtWithRobux = true,
		ID = 3436245434
	}
}
