--[[
Hello there new scripter! just wanted to give you this money effect module that you can use for the game.
here is an example on how to use it:

game.ReplicatedStorage.Remotes.ClientMoneyEffect:FireClient(player, 50, script.Parent.Position)

--You will replace the "50" with the amount of coins its giving
--and the "script.Parent.Position" will be the pigeon's humanoidrootpart [its the position of where the money will come out from.]
]]